#!/usr/bin/env ruby

require 'rubygems'
require 'aws/s3'

release = ARGV[0]
throw "Must provide a release name" unless release 

release_zip = "Flint_#{release}.zip"
release_ovf = "Flint_#{release}.ovf.zip"
release_tarball = "../flint-#{release}.tgz"



AWS::S3::Base.establish_connection!(
                                    :access_key_id => ENV['AMAZON_ACCESS_KEY_ID'],
                                    :secret_access_key => ENV['AMAZON_SECRET_ACCESS_KEY']
                                    )


FLINT_BUCKET='matasano_flint'

begin
  bucket = AWS::S3::Bucket.find(FLINT_BUCKET)
rescue AWS::S3::NoSuchBucket
  bucket = AWS::S3::Bucket.create(FLINT_BUCKET)
end

AWS::S3::Bucket.enable_logging_for(FLINT_BUCKET)

puts "Uploading #{release_zip} to the #{FLINT_BUCKET} bucket."
AWS::S3::S3Object.store(release_zip, open(release_zip), FLINT_BUCKET,
                        :access => :public_read)
puts "Available at #{AWS::S3::S3Object.url_for(release_zip, FLINT_BUCKET, :authenticated => false)}"

puts "Uploading #{release_ovf} to the #{FLINT_BUCKET} bucket."
AWS::S3::S3Object.store(release_ovf, open(release_ovf), FLINT_BUCKET,
                        :access => :public_read)
puts "Available at #{AWS::S3::S3Object.url_for(release_ovf, FLINT_BUCKET, :authenticated => false)}"

puts "Uploading #{release_tarball} to the #{FLINT_BUCKET} bucket."
AWS::S3::S3Object.store(release_tarball, open(release_tarball), FLINT_BUCKET,
                        :access => :public_read)
puts "Available at #{AWS::S3::S3Object.url_for(release_tarball, FLINT_BUCKET, :authenticated => false)}"


