#!/usr/bin/env ruby

flintpath = File.expand_path(File.dirname(__FILE__) + "/../lib")
$LOAD_PATH.unshift flintpath
require 'rubygems'
require 'flint'

# Nuke everything that is already there!
Ohm.flush
